apiVersion: v1
kind: ConfigMap
metadata:
  name: faucet-{{ .Values.Instance }}-configuration
  labels:
    app: faucet
    instance: {{ .Values.Instance }}
data: 
  faucet.yaml: |-
{{ .Values.Configuration | indent 4 }}