apiVersion: v1
kind: Service
metadata:
  name: {{ template "faucet.fullname" . }}
  labels:
    app: {{ template "faucet.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:  
  - name: "6653"
    port: 6653
    targetPort: 6653
    nodePort: 6653
  - name: "9302"
    port: 9302
    targetPort: 9302
    nodePort: 9302
  selector:
    app: {{ template "faucet.name" . }}
    instance: {{ .Values.Instance }}
status:
  loadBalancer: {}
