apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gauge.fullname" . }}
  labels:
    app: {{ template "gauge.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      app: {{ template "gauge.name" . }}
      instance: {{ .Values.Instance }}
      release: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: GAUGE_CONFIG
          value: /etc/faucet/gauge.yaml
        image: faucet/gauge:latest
        name: gauge
        ports:
        - containerPort: 6653
        - containerPort: 9303
        resources: {}
        volumeMounts:
        - mountPath: /var/log/faucet
          name: gauge-claim0
        - mountPath: /etc/faucet
          name: gauge-claim1
      restartPolicy: Always
      volumes:
      - name: gauge-claim0
        persistentVolumeClaim:
          claimName: gauge-claim0
      - name: gauge-claim1
        persistentVolumeClaim:
          claimName: gauge-claim1
status: {}
