apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: {{ template "grafana.name" . }}
    instance: {{ .Values.Instance }}
status:
  loadBalancer: {}
