apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
    app: {{ template "influxdb.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      app: {{ template "influxdb.name" . }}
      instance: {{ .Values.Instance }}
      release: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_PASSWORD
          value: faucet
        - name: INFLUXDB_ADMIN_USER
          value: faucet
        - name: INFLUXDB_DB
          value: faucet
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        image: influxdb:1.6-alpine
        name: influxdb
        ports:
        - containerPort: 8086
        - containerPort: 8083
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-claim0
      restartPolicy: Always
      volumes:
      - name: influxdb-claim0
        persistentVolumeClaim:
          claimName: influxdb-claim0
status: {}
