apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      app: {{ template "prometheus.name" . }}
      instance: {{ .Values.Instance }}
      release: {{ .Release.Name }}
    spec:
      containers:
      - image: prom/prometheus:v2.6.1
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
        - mountPath: ~/faucet/prometheus
          name: prometheus-claim0
        - mountPath: ~/faucet/etc/prometheus/prometheus.yml
          name: prometheus-claim1
        - mountPath: ~/faucet/etc/prometheus/faucet.rules.yml
          name: prometheus-claim2
      restartPolicy: Always
      volumes:
      - name: prometheus-claim0
        persistentVolumeClaim:
          claimName: prometheus-claim0
      - name: prometheus-claim1
        persistentVolumeClaim:
          claimName: prometheus-claim1
      - name: prometheus-claim2
        persistentVolumeClaim:
          claimName: prometheus-claim2
status: {}
