apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    app: {{ template "prometheus.name" . }}
    instance: {{ .Values.Instance }}
status:
  loadBalancer: {}
